### ISSUE TITLE
Big talker couldnt announce 

### ISSUE THREAD

**Issue by bucks7756** [rayzurbock/SmartThings-BigTalker#1]
Yesterday evening,  I started receiving big talker can't announce messages but it still does work.  Anyone else see this happening.

**Comment by rayzurbock** [comment]
Yes.  This has been reported.  This is a SmartThings platform/backend issue with their textToSpeech API function.  Once they fix the platform issue BigTalker should begin working for you again.  Note, this only affects those using BigTalker in musicPlayer mode.  Those using BigTalker in speechSynthesis mode with speechSynthesis supported devices do not see this issue since text to speech is processed in the device and not by SmartThings.  You can follow along here:  https://community.smartthings.com/t/tts-not-working/48651
