### ISSUE TITLE
Big Talker sent refresh command to... sent twice per minute to each TTS device.

### ISSUE THREAD

**Issue by markmarino** [rayzurbock/SmartThings-BigTalker#13]
I think the answer to this is probably "because that's the way it's supposed to work" but when I look a the Activity Feed in my ST app, I see "Big Talker sent refresh command to Samsung R3", and "Big Talker sent refresh command to Samsung M3" sent every minute twice (so 4 times a minute in total).  Is this expected behavior even when everything is "idle"?  Will Big Talker 2 work the same way?

**Comment by rayzurbock** [comment]
Do you have 2 instances of BigTalker running with the same Samsung R3 in each or perhaps have the Samsung R3 configured in the default speech devices as well as in an event override speech device?

BigTalker when in musicPlayer mode instructs SmartThings to poll configured musicPlayer devices once per minute in order to more successfully use the resume feature.  Devices that were not polled may not send updated play,pause,stop status often enough to prevent for example a stopped playlist from starting again after speech has occurred (because SmartThings doesn't have the information that it has stopped yet; thus the poll is an attempt to get this information faster).  

In the 2.0 development version polling is configurable with an on/off toggle so you can control if you want polling or not.

**Comment by rayzurbock** [comment]
@markmarino Did you see the Jul 31 response to this?

2.0 development branch code is here:
https://github.com/rayzurbock/SmartThings-BigTalker/tree/development/smartapps/rayzurbock

2.0 ST Community discussion is here: 
https://community.smartthings.com/t/bigtalker-2-0-development/55305/

**Comment by rayzurbock** [comment]
This is configurable in the 2.0 development release.  You can disable/enable this functionality as you wish for musicPlayer mode.  I hope to graduate this version to regular release the next couple of weeks.
http://thingsthataresmart.wiki/index.php?title=BigTalker
