### ISSUE TITLE
Option to turn off "resume music"

### ISSUE THREAD

**Issue by alexruffell** [rayzurbock/SmartThings-BigTalker#2]
I am creating this issue under the new BT repository just in case the one in the former repository gets forgotten. For yet to be determined issues my BigTalker dedicated Sonos speaker often starts playing music after playing a message even though the speaker was not playing anything. I found a way to break the resume music functionality by searching for "playing" in the source code and prepending my initials to it. Once I do this the random and unfortunately very frequent music playing stops... It would be fantastic if one could have the option to switch this feature off.

On a side note, I do not play music on the Sonos dedicated to home automation use because it would be terribly annoying for the music to get interrupted every time a message is played (mostly open/close  exterior doors).

Another note I should add is that these doors do not have zwave sensors on them but are rather monitored by my DSC alarm. I have a Raspberry Pi 3 running SmartAlarm to interface the DSC alarm to ST... this may be part of why nobody else seems to be having this issue...

**Comment by rayzurbock** [comment]
Thanks.  I'll add the ability to enable/disable resuming music.

**Comment by ericvitale** [comment]
I also have this issue. I am a new user so I can't say if it was always there or just in a recent update. I can  say it is likely not a speaker issue because I don't have this issue with other SmartApps that use my Speakers... Not using Sonos, using HEOS (DNLA).

**Comment by alexruffell** [comment]
Just wanted to confirm that with 1.1.7 the issue is still present therefore I had to purposefully break the code once again to make it work without music starting randomly.

@ericvitale - thank you for the confirmation it is likely not related to Sonos... I was about to attempt setting up a cheap VLC Thing on a RPI to vet that out. I wonder why this doesn't seem to be a more frequent issue with other users.

**Comment by rayzurbock** [comment]
Care to test code?  

**Alpha test code (currently 1.1.8a2 9/8/2016) here:** [https://raw.githubusercontent.com/rayzurbock/SmartThings-BigTalker/development/smartapps/rayzurbock/big-talker-dev.src/big-talker-dev.groovy](https://raw.githubusercontent.com/rayzurbock/SmartThings-BigTalker/development/smartapps/rayzurbock/big-talker-dev.src/big-talker-dev.groovy)
1.1.8a2 development notes:

- I think I squashed a couple of bugs that may have missed playback or caused playback that wasn't desired for musicPlayer devices (Sonos, etc).
- There is a %description% variable that will stay.
- There is also a %devicename2% and %devicename3% variable for testing that will go away.

**Comment by alexruffell** [comment]
I updated the smart app to 1.1.8a2 to test it. Within a few minutes I was able to get it to play music after a message was played when no music was playing prior. The open/close messages of the exterior doors did not seem to trigger the issue however the front door announces when the door is locked/unlocked/open and closed so there is a higher chance of messages back to back. I wonder whether the "is it playing" check catches the message playing so it tells it to resume playing music after the messaged played while in reality it just detected a message playing. Could it be?

**Comment by josharmour** [comment]
I'm also having this issue and can help troubleshoot.  I have two sonos devices and several door sensors.  When a door sensor is detecting as opening or closing - some of the time - it will cause the sonos downstairs (not the one upstairs) to resume music playlist that it was not playing before the sensor triggered.

**Comment by alexruffell** [comment]
@josharmour the link @rayzurbock posted above for 1.1.8a2, now actually pointing to a 1.1.9 alpha code revision fixed my issue 100% however I have only enabled one sonos to do the announcements so my use case is slightly different. I'd give that revision a try and comment back.

**Comment by rayzurbock** [comment]
See 1.1.9.a3.6 in the development branch for this feature.
It does need some testing.
Please do not overwrite your existing BigTalker code with this code.  Instead, create a new SmartApp in the IDE from code and paste the code for this version in.  Go to the SmartThings Marketplace > My Apps and install Big Talker-Dev.  After install from here, it should then be located in the SmartThings app at Automation > SmartApps > BigTalker-Dev.
To reduce confusion, I recommend removing any related automation's from your main BigTalker app prior to testing specific events (switch on/off, motion active/inactive, etc) for disabling resume play functionality to be sure that only the select events are being triggered by this development version.

1.1.9.a3.6 (among other enhancements/changes in the 1.1.9.a development branch) adds the following enhancement:
Added global option to enable/disable resume as well as per event group.
Note: once global option is set, any event saves will save whatever the global option was at the time to the events setting; therefore saving an event when the global is enabled will not disable resume for this event if the global option is changed to disable.

Other updates from 1.1.8 include but are not limited to (this list is still being compiled):

- Additional Talk() debug logging
- Test variables for null with safe navigation operator (?) in more places within Talk().
- Testing resolution to musicPlayer playing text and resuming/restoring.
- Clear state.polledDevices on initialize
- in musicPlayer mode, def Talk() gives currentTrack.status precedence over currentStatus if it exists as it seems more accurate in testing.
- If default speech volume was not set, speech may not have occurred due to a null variable issue. Resolved with groovy safe navigation operator
- Added AskAlexa support (send phrase to AskAlexa queue) with %askalexa% in the phrase.
- Removed requirement to set a speechDevice for users that only wish to use another supported SmartApp to offload/handle the speech - ie: AskAlexa
- Added Smart Home Monitor status events (speak on Arm-Away, Arm-Stay, Disarm)
- Device/SmartApp output detection logging (did we send to a device? did we only send to a SmartApp (AskAlexa), did we send a phrase but didn't send to a device or another SmartApp?)
- Option to disable resume globally and/or per event.

[Code link: https://raw.githubusercontent.com/rayzurbock/SmartThings-BigTalker/development/smartapps/rayzurbock/big-talker-dev.src/big-talker-dev.groovy](https://raw.githubusercontent.com/rayzurbock/SmartThings-BigTalker/development/smartapps/rayzurbock/big-talker-dev.src/big-talker-dev.groovy) 
Please check the version for updates as this link is to a live development version that may change frequently.

Awaiting feedback....

**Comment by rayzurbock** [comment]
1.1.9a3.6 was bad.  I'm sorry.  Please update to 1.1.9a4.0 if you are running the development branch and let me know how it goes.
https://raw.githubusercontent.com/rayzurbock/SmartThings-BigTalker/development/smartapps/rayzurbock/big-talker-dev.src/big-talker-dev.groovy

**Release notes from 1.1.9a3.6 to 1.1.9a4.0:**

- 1.1.9a3.7
  - A lot of work on Talk() and others
  - Pulled the code into Notepad++ where I could work with it better, collapse conditions, etc.  
  - Found several bugs in the Talk() function that I didn't see otherwise.  Squashed.
  - Added a "Poll Now" toggle to the BT main screen, when in Debug and musicPlayer mode.
  - Corrected my very bad implementation of the Resume/Don't Resume option for musicPlayer mode. That was bad code, sorry!
  - SmartThings IDE logs are randomly showing logs. I don't think this is BigTalker related.  It just randomly skips showing logs which I rely on for development and debugging.  It's broken. I hope that the code works properly though, either way this is a better development release than that last poor excuse for one!
- 1.1.9a3.8
  - Added option to disable periodic polling for musicPlayer mode (_some users were concerned with BigTalker showing up in the "Activity" feed so often. If music starts playing after speech when it wasn't before, please make sure that polling is enabled_)
  - When resume is enabled and in musicPlayer mode and in Debug mode, main menu now has an option to cause an instant poll "DEBUG: Poll Now (simply toggle)".
- 1.1.9a3.9
  - Corrected a missed null check in Talk() regarding an empty phrase.
  - Added a null check in Talk() for resume var.
  - Added logging and in-app notification if Talk() is called on an empty phrase.
- 1.1.9a4.0
  - Added Button Held event. (needs testing. I do not have a zwave button)
  - Renamed SHM Stay to SHM Hold to match the language in the SmartApp Dashboard.
  - Additional null checks in Talk() (specifically addressed if the desired phrase only had %askalexa%; throw an error in the logs and notify via push that there is a configuration error due to a missing phrase)

**Comment by rayzurbock** [comment]
This was released in Big Talker 1.1.10. BigTalker is now at 1.1.12.
Thanks for the request. I'm sure it will be useful to many users.

**Comment by alexruffell** [comment]
Thank you for adding the feature. BigTalker has been working very well lately. Some back to back messages cut each other off but I would expect that given the proximity of the events. No music starting after any of the messages without having to change anything in your code so I think the issue has been fixed. Thanks so much!
