### ISSUE TITLE
Weird delays and wrong messages since latest update.

### ISSUE THREAD

**Issue by markmarino** [rayzurbock/SmartThings-BigTalker#8]
Hi Brian - 

I'm running latest version 1.1.12 and since I updated, I've been experiencing issues with long delays after an event occurs (30 seconds after closing front door, getting tts to my Samsung M3 "front door is now closed"... seems to happening for all trigger events.  Also getting some erroneous messages like when I close the front door, Big Talker says "BACK door is now closed".  Also seeing some bad ST behavior where using my Minimote to turn on lights in my bedroom has a long delay... sometimes a minute or longer, but it's not consistent, sometimes it works almost instantaneously too.  

Not sure these are related to Big Talker or something else, but everything was working great until around the time I updated to 1.1.12.  I just turned on debug logging so I will send the log along once I capture something not working right.

**Comment by rayzurbock** [comment]
SmartThings is rolling out a hub update to all V2 hubs. I've seen various delays in the IDE and mobile app recently. Let's give them a few days to finish the roll-out and see where we're at.

________________________________

**Comment by tuhinz** [comment]
Running 2.0.a7 (both parent & child) - I believe thisis a related issue?

In my case, the mode change trigger picks up the correct %lastmode% value but the spoken text generated picks up a different value (which is always the same and is the name I had given to one of the modes but have changed the mode name since).

See log:
Last Mode is correctly identified as "Home" but the spoken text output somehow defines the %lastmode% variable as "free roam" instead of "Home".

I do not have a mode named "free roam" any more but regardless of which mode I change from, the %lastmode% value in the spoken text always defaults to "free roam".


22:43:43: trace BIGTALKER-DEV-PARENT(P-2.0.a7) || [PARENT] TALK(Common_mode-presense_change.mode) |sS| Nexus7_AudioHook | Sending speak().
22:43:43: trace BIGTALKER-DEV-PARENT(P-2.0.a7) || [PARENT] TALK(Common_mode-presense_change.mode) |sS| >> Home mode has changed from free roam to Downstairs.
22:43:43: debug BIGTALKER-DEV-PARENT(P-2.0.a7) || [PARENT] addPersonalityToPhrase(Home mode has changed from free roam to Downstairs.,physicalgraph.app.EventWrapper@7af0db9c)
22:43:43: debug BIGTALKER-DEV-PARENT(P-2.0.a7) || [CHILD:Common_mode-presense_change] (onModeEvent): Last Mode: Home, New Mode: Downstairs

**Comment by rayzurbock** [comment]
@markmarino this issue is in regards to BigTalker 1.1.12.  All development efforts have been moved to the 2.0 branch.  Please try the latest in the 2.0 branch and see if your reported issue is resolved.
https://github.com/rayzurbock/SmartThings-BigTalker/tree/development/smartapps/rayzurbock

@tuhinz, this issue was resolved in BigTalker Parent App version "P2.0.a9" and Child App version "C2.0.a8" and a note was added to your published isse https://github.com/rayzurbock/SmartThings-BigTalker/issues/14 

I'm going to go ahead and close this.  I hope that you find these issues are resolved in the latest version of the 2.0 development branch
